mid month npt fix for 1095A values
ideacrew/edi_gateway pull request #165
Opened 2024-12-26 20:07 UTC by erubinst

2024-12-31 20:42 UTC, nks2109 requested changes
The code looks good, but it needs some refactoring as we use the same code across three files. Refactor date-related methods into a new DateHelper module

- Extracted mid_month_end? and eom_end? methods from app/models/insurance_policies/aca_individuals/enrollment.rb and insurance_policy.rb
- Created a new DateHelper module to centralize date-related calculations
- Included DateHelper in relevant classes for improved code reusability and maintainability

This refactoring adheres to the DRY principle and simplifies future updates.
```
# frozen_string_literal: true

# Helper methods for date-related calculations
module DateHelper
  def mid_month_end?(end_on, month)
    ends_this_month = end_on.month == month
    last_day_of_month = Date.new(end_on.year, month, -1)
    (end_on.day != last_day_of_month.day) && ends_this_month
  end

  def eom_end?(end_on, month)
    ends_this_month = end_on.month == month
    last_day_of_month = Date.new(end_on.year, month, -1)
    (end_on == last_day_of_month) && ends_this_month
  end
end
```

2024-12-31 20:42 UTC, nks2109 commented on app/models/insurance_policies/aca_individuals/enrollment.rb
> +
these mid_month_end?(end_on, month) & eom_end?(end_on, month) methods are used in other files

2025-01-02 00:35 UTC, erubinst commented on app/models/insurance_policies/aca_individuals/enrollment.rb
> +
Thanks, good idea.  I have added the module, let me know if this is what you were expecting.

2025-01-02 14:46 UTC, nks2109 approved these changes
Good work!

2025-01-06 14:39 UTC, nks2109 approved these changes

2025-01-06 14:39 UTC, merged